### ISSUE TITLE
Change Order status does not check current status

### ISSUE THREAD

**Issue by Web10-Joris** [damcclean/simple-commerce#1110]
### Behaviour when multiple Placed status in Status Log

When an order is already status `Placed`, and you try to change the status to`Placed` again using the Action it will write additional `status_log` entry in the database. Causing the `orderDate` to be mixed up. When an order has 2 status `Placed` items in its `status_log` it will show up twice in the CP Orders overview with the latest date on both rows. 

Maybe add a check in the Action that it can not set to the same status? Or prevent from having two times a `Placed` `status_log` (overwrite the old one). Because when changing back to `Placed` the same thing happens. 

---

### Status log updated twice
And I'm not sure if this is only my setup or general, but when changing the Order Status using that action it actually duplicates it in the database with 2 items. So when setting the status of order X once to `Dispatched`, it puts this in the database:

| id | order_id | status     | timestamp           | data                             |
|----|----------|------------|---------------------|----------------------------------|
| 18 | 12577    | dispatched | 2024-07-19 09:51:53 | {"user": 1, "reason": "test"}    |
| 19 | 12577    | dispatched | 2024-07-19 07:51:53 | {"user": 1, "reason": "test"}    |

Can this be due to the timezone setting? I see an exact 2 hour difference in those rows. 

### Steps to reproduce

1. Add order in database with status Placed
2. Change it to status Placed using action. 
4. The order will show up twice in the Orders overview with latest date. 

### Environment

Environment
Application Name: Local
Laravel Version: 11.16.0
PHP Version: 8.3.7
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: de

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR
Gateways: Mollie
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: collect
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 4
Sites: 3 (Nederlands, English, German)
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.14.0 PRO

Statamic Addons
aerni/advanced-seo: 2.7.0
aerni/font-awesome: 2.1.1
duncanmcclean/simple-commerce: 7.3.2
statamic-rad-pack/runway: 7.7.0

**Comment by duncanmcclean** [comment]
The whole "status log" concept doesn't really make much sense, since a status can't *really* happen multiple times (apart from maybe a refund). 

I'm planning to flatten it back to simple `paid_at`/`shipped_at` timestamps in a future version to avoid confusion.

However, for now, it might just be easiest if we update the action so it doesn't let you pick from *past* statuses. I'll take a look when I have some available time, if someone doesn't beat me to it with a PR.

**Comment by Web10-Joris** [comment]
All clear, thanks Duncan! For me the same, when I have time I can look into it for a PR.

**Comment by duncanmcclean** [comment]
> However, for now, it might just be easiest if we update the action so it doesn't let you pick from past statuses. I'll take a look when I have some available time, if someone doesn't beat me to it with a PR.

Just had a look at this - it doesn't look like we can hide past statuses from the dropdown, since the `fieldItems` method doesn't have any context of the items you're selecting. 

The best we could do is throw an error/warning when you actually run the action, but that's not a great solution.

Like I said, this will be fixed in the next major version of Simple Commerce (which is a couple months out at this point), since the actions will likely be simplified to "Mark as Paid", "Mark as Shipped", etc.

As a workaround for now, you can disable the "Update Order Status" action in your `simple-commerce.php` config file and build your own action instead:

```php
'disable_order_status_actions' => true,
```
