### ISSUE TITLE
Block emails

### ISSUE THREAD

**Issue by barchard** [damcclean/simple-commerce#491]
### What would you like to see added?

The ability to define a blacklist of email addresses to block from ordering (e.g., due to fraud claims or other issues. I don't want to do business with them and have them order anything else from the store)

### Is there a workaround you can use in the meantime?

no

### Priority wise - where's this feature for you?

Nice to have

**Comment by duncanmcclean** [comment]
Thanks for opening an issue! 

Although, I think this is probably something left to be done on a store-by-store basis. 

Some people might want different behaviour when a blocked email tried to do an order, might have customers stored a different way or or block due to some other factor (country, etc). At that point, it's not very 'simple' anymore 😂 

I'll open an issue on the other repo :)

**Comment by barchard** [comment]
Yes or a separate add-on for this to give some control over handling. Typically we capture date time, email, external and internal reason. I'll comment on the other issue once opened.
