### ISSUE TITLE
Price and Total variables should respect configured tax.included_in_prices config

### ISSUE THREAD

**Issue by chellmann** [damcclean/simple-commerce#547]
### What would you like to see added?

When tax.included_in_prices config is set to true {{ items_total }} should be set including tax.

To not introduce a breaking change, new variables could be defined like {{ items_total_gross }} 

### Is there a workaround you can use in the meantime?

no

### Priority wise - where's this feature for you?

Blocker

**Comment by duncanmcclean** [comment]
When you toggle `included_in_prices`, it means that the prices you enter for your products already include tax. Meaning, the tax will be deducted from the product when it's added to a customer's cart.

If you need the tax amounts on a per line-item basis, [see this comment](https://github.com/doublethreedigital/simple-commerce/issues/530) on another issue with a solution.

On a cart level, you'll have a few different amounts:

* `items_total` which is the total of all line items, minus any tax
* `tax_total` which is the total of tax from all line items
* `grand_total` which is the total of all items, plus tax

I hope that helps to fix your issue and clear up any confusion!

_FYI: In the next version of Simple Commerce (v2.4), Tax works a little differently so you'll be able to grab the tax amount on the line item if you need it, rather than using a custom modifier._
