### ISSUE TITLE
Blueprint fields missing in order view after database migration

### ISSUE THREAD

**Issue by itsmesaskovic** [damcclean/simple-commerce#634]
### What's the issue you're running into?

In version V2.* we added a number of fields to the order blueprint like radio_dhl_servicepoint, dhl_servicepoint_name and optional_donation. After the update to V3.0.* and migration to the database these fields are available, as JSON, in the orders table in a column called data. But we are not able to view these fields anymore in the Order (now Runway) view.

Can you point me in the right direction (e.g. documentation / video or...) where I can see more about how to configure this so that in CP these custom (Blueprint) fields, like DHL servicepoint, are shown?

### Steps to reproduce

1. Create custom fields in the order blueprint (V2.*)
2. Upgrade to V3.0.*
3. Migrate to the database
4. View (missing) fields in the CP Runway Order view

### Environment

Statamic 3.3.12 Pro
Laravel 8.83.13
PHP 8.0.19
doublethreedigital/runway 2.3.5
doublethreedigital/simple-commerce 3.0.4
joetannenbaum/antlers-stack-tags 0.1.0
optimoapps/statamic-bard-text-align 1.0.2
roorda-ict/statamic-entries-export 1.0.0

**Comment by duncanmcclean** [comment]
I think the best way to do this will be to let you add your own columns to the `order` table if you want them to be editable with Runway.

Simple Commerce will just need to be smart and save to your custom database column, rather than the JSON `data` column.

I probably won't get to this tonight but should have it fixed this week.

**Comment by itsmesaskovic** [comment]
Clear, thank you @duncanmcclean. Looking forward to this update.

**Comment by duncanmcclean** [comment]
Released in v3.1.0 (link in comment above)

If you add the custom columns you need via a database migration, you should be able to set them like you could before and they'll be persisted in your custom column, rather than in the `data` column.

Bear in mind: you'll need to install the [`doctrine/dbal`](https://packagist.org/packages/doctrine/dbal) package when updating.

**Comment by itsmesaskovic** [comment]
Thank you for the fixes Duncan! We have been able to release a new version using your updates.
